package acidicoala.koalageddon.core.values

import acidicoala.koalageddon.BuildConfig

sealed class Strings(
    val appId: String = "App ID",
    val autoInjectInventory: String,
    val checkForUpdates: String,
    val clearCache: String,
    val computing: String,
    val configuration: String,
    val defaultAppStatus: String,
    val dlcId: String = "DLC ID",
    val downloadingRelease: String,
    val extraInventoryItems: String,
    val fetchingToolInfo: String,
    val gameMode: String,
    val inDevelopment: String,
    val install: String,
    val installation: String,
    val installationError: String,
    val installationStatus: String,
    val installationSuccess: String,
    val installed: String,
    val itemId: String = "Item ID",
    val language: String,
    val languageEn: String = "English",
    val languageRu: String = "Русский",
    val logging: String,
    val modifyInstallation: String,
    val openDataDirectory: String,
    val overrideAppStatus: String,
    val overrideDlcStatus: String,
    val notInstalled: String,
    val refreshStatus: String,
    val reloadConfig: String,
    val reloadConfigSuccess: String,
    val reloadConfigError: String,
    val settings: String,
    val statusOriginal: String,
    val statusUnlocked: String,
    val statusLocked: String,
    val storeMode: String,
    val storeSteam: String = "Steam",
    val theme: String,
    val themeDark: String,
    val themeLight: String,
    val toolConfig: String,
    val toolDll: String = "%0 DLL",
    val removalError: String,
    val removalSuccess: String,
    val remove: String,
    val unlockFamilySharing: String,
    val version: String,
) {
    object English : Strings(
        autoInjectInventory = "Automatically inject items into a game's Steam inventory",
        checkForUpdates = "Check for updates",
        clearCache = "Clear cache",
        computing = "Computing",
        configuration = "Configuration",
        defaultAppStatus = "Default game status",
        downloadingRelease = "Downloading %0 release: %1 out of %2",
        extraInventoryItems = "Inject extra items into a game's Steam inventory",
        fetchingToolInfo = "Fetching %0 info",
        gameMode = "Game mode",
        inDevelopment = "In development",
        install = "Install",
        installation = "Installation",
        installationError = "❌ Installation error",
        installationStatus = "Installation status",
        installationSuccess = "✅ Installation was successful",
        installed = "Installed %0",
        language = "Language",
        logging = "Logging",
        modifyInstallation = "Modify installation",
        openDataDirectory = "Open data directory",
        overrideAppStatus = "Override game status",
        overrideDlcStatus = "Override DLC status",
        notInstalled = "Not installed",
        refreshStatus = "Refresh status",
        reloadConfig = "Reload configuration",
        reloadConfigSuccess = "✅ Configuration was successfully reloaded",
        reloadConfigError = "❌ Error reloading configuration",
        settings = "Settings",
        statusOriginal = "Original",
        statusUnlocked = "Unlocked",
        statusLocked = "Locked",
        storeMode = "Store mode",
        theme = "Theme",
        themeDark = "Dark",
        themeLight = "Light",
        toolConfig = "%0 config",
        removalError = "❌ Removal error",
        removalSuccess = "✅ Removal success",
        remove = "Remove",
        unlockFamilySharing = "Unlock Family Sharing",
        version = "Version v${BuildConfig.APP_VERSION}",
    )

    object Russian : Strings(
        autoInjectInventory = "Автоматически внедрять предметы в игровой Steam инвентарь",
        checkForUpdates = "Проверить обновления",
        clearCache = "Очистить кэш",
        computing = "Вычисляется",
        configuration = "Конфигурация",
        defaultAppStatus = "Статус игр по умолчанию",
        downloadingRelease = "Загрузка %0 релиза: %1 из %2",
        extraInventoryItems = "Внедрить дополнительные предметы в игровой  Steam инвентарь",
        fetchingToolInfo = "Получение данных %0",
        gameMode = "Режим игры",
        inDevelopment = "В разработке",
        install = "Установить",
        installation = "Установка",
        installationError = "❌ Ошибка установки",
        installationStatus = "Статус установки",
        installationSuccess = "✅ Установка прошла успешно",
        installed = "Установлено %0",
        language = "Язык",
        logging = "Логирование",
        modifyInstallation = "Изменить установку",
        openDataDirectory = "Открыть директорию данных",
        overrideAppStatus = "Заменить статус игры",
        overrideDlcStatus = "Заменить статус DLC",
        notInstalled = "Не установлено",
        refreshStatus = "Обновить статус",
        reloadConfig = "Перезагрузить конфигурацию",
        reloadConfigSuccess = "✅ Конфигурация успешно перезагружена",
        reloadConfigError = "❌ Ошибка перезагруки конфигурации",
        settings = "Настройки",
        statusOriginal = "Оригинальный",
        statusUnlocked = "Разблокированный",
        statusLocked = "Заблокированный",
        storeMode = "Режим магазина",
        theme = "Тема",
        themeDark = "Тёмная",
        themeLight = "Светлая",
        toolConfig = "Конфигурация %0",
        removalError = "❌ Ошибка удаления",
        removalSuccess = "✅ Удаление прошло успешно",
        remove = "Удалить",
        unlockFamilySharing = "Разблокировать Family Sharing",
        version = "Версия v${BuildConfig.APP_VERSION}",
    )
}


