package acidicoala.koalageddon.core.values

import acidicoala.koalageddon.BuildConfig

sealed class Strings(
    val checkForUpdates: String,
    val clearCache: String,
    val configuration: String,
    val downloadingLoaderRelease: String,
    val fetchingLoaderInfo: String,
    val gameMode: String,
    val inDevelopment: String,
    val install: String,
    val installation: String,
    val installationStatus: String,
    val installed: String,
    val language: String,
    val languageEn: String = "English",
    val languageRu: String = "Русский",
    val loaderConfig: String,
    val loaderDll: String,
    val modifyInstallation: String,
    val openDataDirectory: String,
    val notInstalled: String,
    val refreshStatus: String,
    val reloadConfig: String,
    val reloadConfigSuccess: String,
    val reloadConfigError: String,
    val settings: String,
    val storeMode: String,
    val storeSteam: String = "Steam",
    val theme: String,
    val themeDark: String,
    val themeLight: String,
    val uninstall: String,
    val unlockerConfig: String,
    val unlockerDll: String,
    val version: String,
) {
    object English : Strings(
        checkForUpdates = "Check for updates",
        clearCache = "Clear cache",
        configuration = "Configuration",
        downloadingLoaderRelease = "Downloading loader release: %1 out of %2",
        fetchingLoaderInfo = "Fetching loader info",
        gameMode = "Game mode",
        inDevelopment = "In development",
        install = "Install",
        installation = "Installation",
        installationStatus = "Installation status",
        installed = "Installed",
        language = "Language",
        loaderConfig = "Loader config",
        loaderDll = "Loader DLL",
        modifyInstallation = "Modify installation",
        openDataDirectory = "Open data directory",
        notInstalled = "Not installed",
        refreshStatus = "Refresh status",
        reloadConfig = "Reload configuration",
        reloadConfigSuccess = "✅ Configuration was successfully reloaded",
        reloadConfigError = "❌ Error reloading configuration",
        settings = "Settings",
        storeMode = "Store mode",
        theme = "Theme",
        themeDark = "Dark",
        themeLight = "Light",
        uninstall = "Uninstall",
        unlockerConfig = "Unlocker config",
        unlockerDll = "Unlocker DLL",
        version = "Version v${BuildConfig.APP_VERSION}",
    )

    object Russian : Strings(
        checkForUpdates = "Проверить обновления",
        clearCache = "Очистить кэш",
        configuration = "Конфигурация",
        downloadingLoaderRelease = "Скачивается релиз загрузчика: %1 из %2",
        fetchingLoaderInfo = "Получение данных загрузчика",
        gameMode = "Режим игры",
        inDevelopment = "В разработке",
        install = "Установить",
        installation = "Установка",
        installationStatus = "Статус установки",
        installed = "Установлено",
        language = "Язык",
        loaderConfig = "Конфигурация загрузчика",
        loaderDll = "DLL загрузчика",
        modifyInstallation = "Изменить установку",
        openDataDirectory = "Открыть директорию данных",
        notInstalled = "Не установлено",
        refreshStatus = "Обновить статус",
        reloadConfig = "Перезагрузить конфигурацию",
        reloadConfigSuccess = "✅ Конфигурация успешно перезагружена",
        reloadConfigError = "❌ Ошибка перезагруки конфигурации",
        settings = "Настройки",
        storeMode = "Режим магазина",
        theme = "Тема",
        themeDark = "Тёмная",
        themeLight = "Светлая",
        uninstall = "Удалить",
        unlockerConfig = "Конфигурация разблокировщика",
        unlockerDll = "DLL разблокировщика",
        version = "Версия v${BuildConfig.APP_VERSION}",
    )
}


